name: get_x
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.3.8
  dio: ^4.0.1
  flutter:
    sdk: flutter
  json_annotation: ^4.3.0
  shared_preferences: ^2.0.8

dev_dependencies:
  build_runner: ^2.1.4
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true
